config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :bookings
  resources :rooms
  resources :patients
  resources :staffs, path: 'staff'
  resources :triage_queues, path: 'triage-queue', only: [:index, :create, :destroy]
  put "triage-queue/reorder", to: 'triage_queues#reorder'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root 'patients#index'
end

app/models/staff.rb
require_dependency 'generics'

class Staff
  include Mongoid::Document
  include ActiveModel::SecurePassword

  field :refNb
  field :password
  field :password_digest, :type => String
  attr_accessor :confirm_pass

  has_secure_password
  field :role

  # Personal Details
  embeds_one :name, class_name: "Name",  as: "nameObj"
  field :DOB, type: Date
  field :gender
  field :address
  embeds_many :phoneNumbers, class_name: "PhoneNumber", as: "phoneNumberObj"

  # Practitioner Details
  field :licenceNb
  field :licenceDate, type: Date
  field :department

  has_and_belongs_to_many :bookings, class_name: "Booking", inverse_of: "practitioners"

  accepts_nested_attributes_for :name
  validates_associated :name

  attr_accessor :skip_password
  validates :password, length: { minimum: 6, message: 'Password must be at least 6 characters.' }, unless: :skip_password
  validate :passCheck, unless: :skip_password

  validates :phoneNumbers, presence: { message: 'At least one phone number must be added.'}
  validates :gender, presence: { message: 'A gender must be specified.' }
  validates :DOB, presence: { minimum: 6, message: 'A date of birth is required.'}
  validates :address, presence: {message: 'Staff address must be entered.'}

  def fullName
    "#{self.name.first} #{self.name.last}"
  end

  def passCheck
    if self.password != self.confirm_pass
      errors.add(:confirm_pass, "Passwords do not match")
    end
  end

  # TODO: We need to validate :licenceNb, licenceDate and department IF :role is Dr.
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staff
  def index
    @staffs = Staff.all
  end

  # GET /staff/1
  def show
    @upcoming_bookings = Booking.where(practitioner_ids:  @staff.id, :endDt.gt => DateTime.now).to_a
  end

  # GET /staff/new
  def new
    @staff = Staff.new
    @staff.build_name
  end

  # GET /staff/1/edit
  def edit
  end

  # POST /staff
  def create
    @staff = Staff.new(staff_params)
    @staff.refNb = Staff.count + 1

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staff/1
  def update
    respond_to do |format|
      if staff_params[:password].eql? ""
        staff_params.delete(:password)
        @staff.skip_password = true
      end
      puts staff_params

      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staff/1
  # Disabled for now, should disable accounts rather than deleting them
  # def destroy
  #   @staff.destroy
  #   respond_to do |format|
  #     format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit!
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<script>phoneNumbersCount = <%= @staff.phoneNumbers.length %>;</script>

<%= form_for @staff do |staff| %>
  <div class="container"><%= staff.fields_for :name do |name| %>
    <h3>Name</h3>
    <div class="form-group row">
      <div class="col-sm-3">
        <label class="control-label">Title</label>
        <%= name.text_field :title, class: 'form-control rounded', value: @staff.name.title %>
        <p class ="text-danger"><%= @staff.name.errors[:title][0] %></p>
      </div>
      <div class="col-sm-3">
        <label class="control-label">First</label>
        <%= name.text_field :first, class: 'form-control rounded', value: @staff.name.first %>
        <p class ="text-danger"><%= @staff.name.errors[:first][0] %></p>
      </div>
      <div class="col-sm-3">
        <label class="control-label">Last</label>
        <%= name.text_field :last, class: 'form-control rounded', value: @staff.name.last %>
        <p class ="text-danger"><%= @staff.name.errors[:last][0] %></p>
      </div>
      <div class="col-sm-3">
        <label class="control-label">Preferred</label>
        <%= name.text_field :preferred, class: 'form-control rounded', value: @staff.name.preferred %>
      </div>
    </div>
  <% end %></div>

  <div class="container">
    <h3>Personal Details</h3>
    <div class="form-group row">
      <div class="col-sm-4">
        <label class="control-label">Date of Birth</label>
        <%= staff.date_field :DOB, class: 'form-control rounded', value: @staff.DOB %>
        <p class ="text-danger"><%= @staff.errors[:DOB][0] %></p>
      </div>
      <div class="col-sm-4">
        <label class="control-label">Gender</label>
        <%= staff.text_field :gender, class: 'form-control rounded', value: @staff.gender %>
        <p class ="text-danger"><%= @staff.errors[:gender][0] %></p>
      </div>
      <div class="col-sm-4">
        <label class="control-label">Address</label>
        <%= staff.text_field :address, class: 'form-control rounded', value: @staff.address %>
        <p class ="text-danger"><%= @staff.errors[:address][0] %></p>
      </div>
    </div>
  </div>

  <div class="container">
    <h3>Account Details</h3>
    <div class="form-group row">
      <div class="col-sm-4">
        <label class="control-label">Role</label>
        <%= staff.select( :role, options_for_select([['Administrator', 'admin'], ['Secretary', 'secretary'], ['Doctor', 'doctor'], ['Nurse', 'nurse']], @staff.role), {}, {class: 'form-control rounded' })%>
      </div>
      <div class="col-sm-4">
        <label class="control-label">Password</label>
        <%= staff.password_field :password, class: 'form-control rounded' %>
        <p class ="text-danger"><%= @staff.errors[:password][0] %></p>
      </div>
      <div class="col-sm-4">
        <label class="control-label">Confirm Password</label>
        <%= staff.password_field :confirm_pass, class: 'form-control rounded' %>
        <p class ="text-danger"><%= @staff.errors[:confirm_pass][0] %></p>
      </div>
    </div>
  </div>

  <div class="container">
    <h3>Phone Numbers</h3>
    <table id="staff_phoneNumbers" class="table">
      <tr>
        <th style="width:25%">Type</th>
        <th width="width:75%">Number</th>
      </tr>
      <% @staff.phoneNumbers.each_with_index do |phoneNumber, index| %>
        <tr>
          <td>
            <input type="hidden" name='staff[phoneNumbers][<%= index %>][id]' value="<%= phoneNumber.id %>"/>
            <select class='form-control' name='staff[phoneNumbers][<%= index %>][type]'>
              <option value='mobile' <%= "selected" if phoneNumber.type.eql? 'mobile' %> > Mobile</option>
              <option value='home' <%= "selected" if phoneNumber.type.eql? 'home' %> >Home</option>
              <option value='work' <%= "selected" if phoneNumber.type.eql? 'work' %> >Work</option>
            </select>
          </td>
          <td><input class='form-control' type='text' name='staff[phoneNumbers][<%= index %>][number]' value="<%= phoneNumber.number %>"></td>
        </tr>
      <% end %>
    </table>
    <button class="btn" type="button" onclick="appendPhoneNumber('staff_phoneNumbers', StaffPhoneNumberHTML)">Add Phone Number</button>
    <p class="text-danger"><%= @staff.errors[:phoneNumbers][0] %></p>
  </div>

  <!-- TODO: This needs to be disabled if the new user is not a practitioner type. -->
  <div class="container">
    <h3>Practitioner Details</h3>
    <div class="form-group row">
      <div class="col-sm-4 form-group" >
        <label class="control-label">Licence Number</label>
        <%= staff.text_field :licenceNb, class: 'form-control rounded', value: @staff.licenceNb %>
      </div>
      <div class="col-sm-4 form-group">
        <label class="control-label">Licence Received</label>
        <%= staff.date_field :licenceDate, class: 'form-control rounded', value: @staff.licenceDate %>
      </div>
      <div class="col-sm-4 form-group">
        <label class="control-label">Department</label>
        <%= staff.text_field :department, class: 'form-control rounded', value: @staff.department %>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="form-group row">
      <div class="col-md-1">
        <button type="submit" class="btn btn-primary rounded">Confirm</button>
      </div>
    </div>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form', staff: @staff %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Staff</h1>

<table class="table">
  <thead>
    <tr>
      <th>Staff Id</th>
      <th>Name</th>
      <th>Role</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody><% @staffs.each do |staff| %>
    <tr>
      <td><%= staff.refNb %></td>
      <td><%= staff.name.first %> <%= staff.name.last %></td>
      <td><%= staff.role %></td>
      <td><%= link_to 'Show', staff %></td>
      <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
    </tr>
  <% end %></tbody>
</table>
<br>
<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1> New Staff </h1>
<%= render 'form', staff: @staff %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Personal Details</h1>
<p>
  <strong>Name:</strong>
  <%= @staff.fullName %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @staff.gender %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= @staff.DOB %>
</p>

<p>
  <strong>Address:</strong>
  <%= @staff.address %>
</p>

<p>
  <strong>Role:</strong>
  <%= @staff.role %>
</p>

<% if ['doctor', 'nurse'].include? @staff.role %>
  <p>
    <strong>Department:</strong>
    <%= @staff.department %>
  </p>

  <h3>Licence Info:</h3>
  <p>
    <%= @staff.licenceNb %>, Received <%= @staff.licenceDate %>
  </p>
<% end %>

<h4>Contacts:</h4>
<ul>
  <% @staff.phoneNumbers.each do |phoneNumber| %>
    <li><%= "#{phoneNumber.type}: #{phoneNumber.number}" %></li>
  <% end %>
</ul>

<% if ['doctor', 'nurse'].include? @staff.role and @upcoming_bookings.length > 0%>
<h4>Upcoming Bookings:</h4>
<ul>
  <% @upcoming_bookings.each do |booking| %>
    <li><%= "#{booking.room.refNb}: #{booking.startDt} - #{booking.endDt}" %></li>
  <% end %>
</ul>
<% end %>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>