config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :bookings
  resources :rooms
  resources :patients
  resources :staffs, path: 'staff'
  resources :triage_queues, path: 'triage-queue', only: [:index, :create, :destroy]
  put "triage-queue/reorder", to: 'triage_queues#reorder'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root 'patients#index'
end

app/models/booking.rb
class Booking
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :room, class_name: "Room", validate: false
  belongs_to :patient, class_name: "Patient", validate: false
  has_and_belongs_to_many :practitioners, class_name: "Staff", validate: false
  field :startDt, type: DateTime
  field :endDt, type: DateTime
  field :status, type: String
  field :notes, type: String

  validates :startDt, presence: {message: 'A start date must be specified'}
  validates :endDt, presence: {message: 'An end date must be specified'}

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  def index
    if ['doctor', 'nurse'].include? @current_user.role
      @bookings = Booking.where(practitioner_ids: @current_user.id)
    else
      @bookings = Booking.all
    end
    @rooms = Room.all
    @patients = Patient.all
    @staff = Staff.all
  end

  # GET /bookings/1
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @booking.startDt = DateTime.now
    @booking.endDt = DateTime.now
    if params[:patient]
      @booking.patient = params[:patient]
    end
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  def create
    if booking_params[:practitioners] and booking_params[:practitioners].length > 0
      booking_params[:practitioners] = Staff.find(booking_params[:practitioners])
    end

    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        queue_item = TriageQueue.find_by(patient_id: @booking.patient.id)
        if queue_item
          queue_item.destroy
        end
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else 
        format.html { redirect_to new_booking_path, notice: @booking.errors }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  def update
    if booking_params[:practitioners] and booking_params[:practitioners].length > 0
      booking_params[:practitioners] = Staff.find(booking_params[:practitioners])
    end

    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit!
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for @booking do |booking| %>
  <% if false and booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
      <ul><% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %></ul>
    </div>
  <% end %>

  <div class="container">
    <div class="form-group row">
      <div class="col-md-4 col-sm-6">
        <label>Booking For</label>
        <% if @booking.patient %>
          <%= booking.hidden_field :patient, value: @booking.patient.id %>
          <input class="form-control" readonly value="<%= @booking.patient.fullName %>"/>
        <% else %>
          <%= booking.select :patient, options_for_select(Patient.all.collect {|patient| ["#{patient.refNb} - #{patient.fullName}", patient.id]}), {}, {class: "form-control"} %>
        <% end %>
      </div>
      <div class="col-md-4 col-sm-6">
        <label>Room Number</label>
        <%= booking.select :room, options_for_select(Room.all.map {|r| [r.refNb, r.id] }), {}, {class: "form-control"} %>
      </div>
      <div class="col-md-4 col-sm-6">
        <label>Practitioners Scheduled</label>
        <%= booking.collection_select :practitioners, Staff.where(:role.in => ['doctor', 'nurse']), :id, :fullName, {include_hidden: false}, {class: "form-control", multiple: true} %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-sm-6">
        <label>Booking Start</label>
        <%= booking.datetime_field :startDt, class: "form-control rounded" %>
        <p class ="text-danger"><%= @booking.errors[:startDt][0] %></p>
      </div>
      <div class="col-sm-6">
        <label>Booking End</label>
        <%= booking.datetime_field :endDt, class: "form-control rounded" %>
        <p class ="text-danger"><%= @booking.errors[:endDt][0] %></p>
      </div>
    </div>
  </div>

  <div class="container">
    <h3>Additional Notes</h3>
    <div class="form-group row">
      <div class="col-sm-12">
        <%= booking.text_area :notes, class: "form-control"%>
      </div>
    </div>
  </div>

  <div class="container">
    <button type="submit" class="btn btn-primary">Confirm Booking</button>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
      $('select').selectpicker();
  });
</script>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Bookings</h1>
<%= link_to 'New Booking', new_booking_path %>
<%= content_tag(:div, "", id: 'booking-container', data: {source: @bookings})%>
<%= content_tag(:div, "", id: 'room-container', data: {source: @rooms})%>
<%= content_tag(:div, "", id: 'patient-container', data: {source: @patients})%>
<br>

<div id="filter" class="form-group row">
  <div class="col-2">
    <select class='form-control' id="filter-mode">
      <option value='room'>Room</option>
      <option value='patient'>Patient</option>
      <option value='staff'>Staff</option>
    </select>
  </div>
  <div class="col-3"><input type="text" class="form-control rounded" id="filter"></div>
  <div class="col-1"><button class="btn" onclick="createSchedule()">Filter</button></div>
  <div class="col-3 offset-3">
    <button class="btn" name="prev">Previous</button>
    <button class="btn" name="today">Today</button>
    <button class="btn" name="next">Next</button>
  </div>
</div>

<div class="form-group row">
  <div id="schedule" style="bottom: 0"></div>
</div>

<table class="table">
  <thead>
  <tr>
    <th>Room</th>
    <th>Patient</th>
    <th>Status</th>
    <th>From</th>
    <th>Til</th>
    <th>Notes</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @bookings.each do |booking| %>
    <tr>
      <td><%= booking.room.refNb %></td>
      <td><%= booking.patient.fullName %></td>
      <td><%= booking.status %></td>
      <td><%= booking.startDt %></td>
      <td><%= booking.endDt %></td>
      <td><%= booking.notes %></td>
      <td><%= link_to 'Show', booking %></td>
      <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
      <td><%= link_to 'Remove', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<script>
    $(document).ready(function() {
        createSchedule();
    })
</script>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @booking.room.refNb %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @booking.patient.fullName %>
</p>

<p>
  <strong>Practitioner(s):</strong>
  <ul>
    <% @booking.practitioners.each do |practitioner| %>
      <li><%= practitioner.fullName %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Status:</strong>
  <%= @booking.status %>
</p>

<p>
  <strong>Booking Start:</strong>
  <%= @booking.startDt %>
</p>

<p>
  <strong>Booking End:</strong>
  <%= @booking.endDt %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @booking.notes %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>