config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :bookings
  resources :rooms
  resources :patients
  resources :staffs, path: 'staff'
  resources :triage_queues, path: 'triage-queue', only: [:index, :create, :destroy]
  put "triage-queue/reorder", to: 'triage_queues#reorder'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root 'patients#index'
end

app/models/patient.rb
require_dependency 'generics'

class Patient
  include Mongoid::Document
  include Mongoid::Timestamps

  field :refNb, type: Integer
  embeds_one :personalDetails, class_name: "PersonalDetails"
  embeds_one :insuranceDetails, class_name: "InsuranceDetails"
  embeds_many :emergencyContacts, class_name: "EmergencyContact"
  #embeds_many :history, as: "Booking"
  #has_many :bookings, as: "Booking"
  has_one :triage_queue, class_name: "TriageQueue"

  accepts_nested_attributes_for :personalDetails
  validates_associated :personalDetails
  
  def fullName
    "#{self.personalDetails.name.first} #{self.personalDetails.name.last}"
  end
end

class PersonalDetails
  include Mongoid::Document

  embeds_one :name, class_name: "Name", as: "nameObj"
  field :gender
  field :DOB, type: Date
  field :email
  embeds_many :phoneNumbers, class_name: "PhoneNumber", as: "phoneNumberObj"
  field :address

  embedded_in :patient, class_name: "Patient", inverse_of: "personalDetails"

  validates_associated :name
  accepts_nested_attributes_for :name
  validates :gender, presence: { message: 'A gender must be specified.' }
  validates :DOB, presence: { message: 'A date of birth must be specified.'}

  validates :phoneNumbers, presence: {message: 'At least one phone number must be added.'}
end

class EmergencyContact
  include Mongoid::Document
  field :name
  field :relation
  field :address
  field :phoneNumber
  field :isNextOfKin, type: Boolean

  embedded_in :patient
end

class InsuranceDetails
  include Mongoid::Document

  field :medicareNumber
  field :medicareRef
  field :medicareExpiry, type: Date

  embedded_in :patient
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update]

  # GET /patients
	# GET /patients.json
	def index
    @patients = Patient.all
    @queue_item = TriageQueue.new
	end

  # GET /patients/1
	# GET /patients/1.json
	def show
	end

	# GET /patients/new
	def new
    @patient = Patient.new
		@patient.build_personalDetails
    @patient.personalDetails.build_name
		@patient.build_insuranceDetails
	end

	# POST /patients
	# POST /patients.json
	def create
    @patient = Patient.new(patient_params)
    @patient.refNb = Patient.count + 1

    respond_to do |format|
		  if @patient.save
			  format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
			  format.html { render :new }
				format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

	# GET /patients/1/edit
	def edit
	end

	# PATCH/PUT /patients/1
	# PATCH/PUT /patients/1.json
	def update
	  respond_to do |format|
			if @patient.update(patient_params)
			  format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
				format.json { render :show, status: :ok, location: @patient }
      else
			  format.html { render :edit }
				format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  private
	# Use callbacks to share common setup or constraints between actions.
	def set_patient
	  @patient = Patient.find(params[:id])
  end

	def patient_params
	  params.require(:patient).permit!
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<script> emergencyContactsCount = <%= @patient.emergencyContacts.length %>;</script>
<script>phoneNumbersCount = <%= @patient.personalDetails.phoneNumbers.length %>;</script>

<%= form_for @patient do |patient| %>
  <div class="container"><%= patient.fields_for :personalDetails do |details| %>
    <h3>Personal Details</h3>
    <div class="form-group row"><%= details.fields_for :name do |name| %>
      <div class="col-sm-3" >
        <label class="control-label">Title</label>
        <%= name.text_field :title, class: 'form-control' %>
        <p class ="text-danger"><%= @patient.personalDetails.name.errors[:title][0] %></p>
      </div>
      <div class="col-sm-3" >
        <label class="control-label">First Name</label>
        <%= name.text_field :first, class: 'form-control' %>
        <p class ="text-danger"><%= @patient.personalDetails.name.errors[:first][0] %></p>
        <p class ="text-danger"><%=  %></p>
      </div>
      <div class="col-sm-3" >
        <label class="control-label">Last Name</label>
        <%= name.text_field :last, class: 'form-control' %>
        <p class ="text-danger"><%= @patient.personalDetails.name.errors[:last][0] %></p>
        <p class ="text-danger"><%=  %></p>
      </div>
      <div class="col-sm-3" >
        <label class="control-label">Preferred Name</label>
        <%= name.text_field :preferred, class: 'form-control' %>
      </div>
    <% end %></div>
    <div class="form-group row">
      <div class="col-sm-3">
        <label class="control-label">Gender</label>
        <%= details.text_field :gender, class: 'form-control' %>
        <p class ="text-danger"><%= @patient.personalDetails.errors[:gender][0] %></p>

      </div>
      <div class="col-sm-3">
        <label class="control-label">Email Address</label>
        <%= details.text_field :email, class: 'form-control' %>
      </div>
      <div class="col-sm-3" >
        <label class="control-label">Date of Birth</label>
        <%= details.date_field :DOB, class: 'form-control' %>
        <p class ="text-danger"><%= @patient.personalDetails.errors[:DOB][0] %></p>
      </div>
      <div class="col-sm-3">
        <label class="control-label">Address</label>
        <%= details.text_field :address, class: 'form-control' %>
        <p class ="text-danger"><%= @patient.personalDetails.errors[:address][0] %></p>
      </div>
    </div>
    <div class="form-group">
      <h4> Phone Numbers </h4>
      <table id="patient_personalDetails_phoneNumbers" class="table">
        <tr>
          <th width="25%">Type</th>
          <th width="75%">Number</th>
        </tr>
        <% @patient.personalDetails.phoneNumbers.each_with_index do |phoneNumber, index| %>
          <tr>
            <td>
              <input type="hidden" name='patient[personalDetails][phoneNumbers][<%= index %>][id]' value="<%= phoneNumber.id %>"/>
              <select class='form-control' name='patient[personalDetails][phoneNumbers][<%= index %>][type]'>
                <option value='mobile' <%= "selected" if phoneNumber.type.eql? 'mobile' %> > Mobile</option>
                <option value='home' <%= "selected" if phoneNumber.type.eql? 'home' %> >Home</option>
                <option value='work' <%= "selected" if phoneNumber.type.eql? 'work' %> >Work</option>
              </select>
            </td>
            <td><input class='form-control' type='text' name='patient[personalDetails][phoneNumbers][<%= index %>][number]' value="<%= phoneNumber.number %>"></td>
          </tr>
        <% end %>
      </table>
      <button class="btn" type="button" onclick="appendPhoneNumber('patient_personalDetails_phoneNumbers', PatientPhoneNumberHTML)">Add Phone Number</button>

      <p class ="text-danger"><%= @patient.personalDetails.errors[:phoneNumbers][0] %></p>
    </div>
  <% end %></div>

  <div class="container">
    <h3>Emergency Contacts</h3>
    <table id="patient_emergencyContacts" class="table">
      <tr>
        <th width="20%">Name</th>
        <th width="20%">Relation</th>
        <th width="20%">Address</th>
        <th width="20%">Phone Number</th>
        <th width="20%">Next of Kin?</th>
      </tr>
      <% @patient.emergencyContacts.each_with_index do |emergencyContact, index| %>
        <input type="hidden" name='patient[emergencyContacts][<%= index %>][id]' value="<%= emergencyContact.id %>"/>
        <tr>
          <td><input class='form-control' type='text' name='patient[emergencyContacts][<%= index %>][name]' value="<%= emergencyContact.name %>"></td>
          <td><input class='form-control' type='text' name='patient[emergencyContacts][<%= index %>][relation]' value="<%= emergencyContact.relation %>"></td>
          <td><input class='form-control' type='text' name='patient[emergencyContacts][<%= index %>][address]' value="<%= emergencyContact.address %>"></td>
          <td><input class='form-control' type='text' name='patient[emergencyContacts][<%= index %>[phoneNumber]' value="<%= emergencyContact.phoneNumber %>"></td>
          <td><input class='checkbox' type='checkbox' name='patient[emergencyContacts][<%= index %>][isNextOfKin]' ></td>
        </tr>
      <% end %>
    </table>
    <button class="btn" type="button" onclick="appendEmergencyContact('patient_emergencyContacts', EmergencyContactHTML)">Add Emergency Contact</button>
  </div>
  <br>

  <div class="container"><%= patient.fields_for :insuranceDetails do |details| %>
    <h3>Insurance Details</h3>
    <div class="form-group row">
      <div class="col-sm-4">
        <label class="control-label">Medicare Number</label>
        <%= details.text_field :medicareNumber, class: 'form-control' %>
      </div>
      <div class="col-sm-4">
        <label class="control-label">Medicare Reference</label>
        <%= details.text_field :medicareRef, class: 'form-control' %>
      </div>
      <div class="col-sm-4" >
        <label class="control-label">Medicare Expiry</label>
        <%= details.date_field :medicareExpiry, class: 'form-control' %>
      </div>
    </div>
  <% end %></div>

  <div class="container">
    <button type="submit" class="btn btn-primary">Confirm Patient</button>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients</h1>

<table class="table">
  <thead>
    <tr>
      <th>Patient #</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td style="vertical-align:middle"><%= patient.refNb %></td>
        <td style="vertical-align:middle"><%= patient.fullName %></td>
        <td style="vertical-align:middle"><%= link_to 'Show', patient %></td>
        <td style="vertical-align:middle"><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td style="vertical-align:middle"><button type="button" onclick="$('#triage_queue_patient').val('<%= patient.id %>')" class="btn btn-primary" style="font-size: 10pt" data-toggle="modal" data-target="#triageModal">Add to Triage Queue</button></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Patient', new_patient_path %>

<div class="modal fade" id="triageModal" tabindex="-1" role="dialog" aria-labelledby="triageModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <%= form_for @queue_item, :url => url_for(controller: "triage_queues", action: :create) do |form| %>
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="triageModal">Notes for Patient Triage</h3>
      </div>
      <div class="modal-body">
          <%= form.hidden_field :patient %>
          <%= form.text_area :notes, class: 'form-control', placeholder: 'Optional'%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Add Patient to Queue</button>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Personal Details</h1>
<p>
  <strong>Name:</strong>
  <%= @patient.fullName %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @patient.personalDetails.gender %>
</p>

<p>
  <strong>Date of Birth:</strong>
  <%= @patient.personalDetails.DOB %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.personalDetails.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.personalDetails.address %>
</p>

<h1>Insurance Details</h1>
<p>
  <strong>Medicare Number:</strong>
  <%= @patient.insuranceDetails.medicareNumber %>
</p>

<p>
  <strong>Medicare Ref:</strong>
  <%= @patient.insuranceDetails.medicareRef %>
</p>

<p>
  <strong>Medicare Expiry:</strong>
  <%= @patient.insuranceDetails.medicareExpiry %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>