config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :bookings
  resources :rooms
  resources :patients
  resources :staffs, path: 'staff'
  resources :triage_queues, path: 'triage-queue', only: [:index, :create, :destroy]
  put "triage-queue/reorder", to: 'triage_queues#reorder'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root 'patients#index'
end

app/models/room.rb
class Room
  include Mongoid::Document
  field :refNb, type: String 
  field :department, type: String

  validates :refNb, presence: {message: 'Room number must be specified.'}
  validates_format_of :refNb, :with => /\A([^@\s]+)-([^@\s]+)\Z/i, message: 'Room format must floor-room.'
  validates :department, presence: {message: 'Department must be specified.'}

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all.order_by(refNb: :asc)
  end

  # GET /rooms/1
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:refNb, :department)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <label class="control-label">Room Number</label>
        <%= form.text_field :refNb, class: 'form-control rounded' %>
        <p class ="text-danger"><%= room.errors[:refNb][0] %></p>
      </div>

      <div class="col-sm-3">
        <label class="control-label">Department</label>
        <%= form.text_field :department, class: 'form-control rounded' %>
        <p class ="text-danger"><%= room.errors[:department][0] %></p>
      </div>
    </div>
    
    <div class = "container">
      <button type="submit" class="btn btn-primary rounded">Register</button>
    </div>
  </div>

  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Rooms</h1>

<table class="table">
  <thead>
    <tr>
      <th>Room</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.refNb %></td>
        <td><%= room.department %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room #:</strong>
  <%= @room.refNb %>
</p>

<p>
  <strong>Department:</strong>
  <%= @room.department %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>